# Docker Compose Configuration for Multi-Container Application
# Defines services (backend and frontend), their dependencies, network configuration, and environment variables


version: "3.8"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://todo-app:zNpGi5ki4CWz47gk@cluster0.xsu99.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=5f2b5cdbe5924ab8d9480e7e689c7c14
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
